apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: restaurant-system

resources:
  - ../../infrastructure/kubernetes/namespace.yaml
  - ../../infrastructure/kubernetes/configmap.yaml
  - ../../infrastructure/kubernetes/secrets.yaml
  - ../../infrastructure/kubernetes/persistent-volumes.yaml
  - ../../infrastructure/kubernetes/postgres-statefulset.yaml
  - ../../infrastructure/kubernetes/redis-statefulset.yaml
  - ../../infrastructure/kubernetes/auth-service-deployment.yaml
  - ../../infrastructure/kubernetes/restaurant-service-deployment.yaml
  - ../../infrastructure/kubernetes/api-gateway-deployment.yaml
  - ../../infrastructure/kubernetes/frontend-deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: restaurant-system
