apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: restaurant-system
type: Opaque
stringData:
  token: eyJhIjoiOGY0YTA1Mzk0Y2NlZmEyYWY1NjMxNjM4NjBlM2E4MWIiLCJ0IjoiMDBkMzRiY2YtYjRhOS00NTFhLTkxM2UtNDA5OTRjMDE1YjExIiwicyI6Ik1qaGtObUV6TW1NdE5UYzJaaTAwTURaakxXSmpZV0V0TkROaFpqRmtPVEptWldVMiJ9
