{{- if .Values.authService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.authService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "restaurant-system.authService.labels" . | nindent 4 }}
spec:
  type: {{ .Values.authService.service.type }}
  ports:
  - port: {{ .Values.authService.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.authService.name }}
{{- end }}
