apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-token
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "restaurant-system.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: "eyJhIjoiOGY0YTA1Mzk0Y2NlZmEyYWY1NjMxNjM4NjBlM2E4MWIiLCJ0IjoiMDE3Mjg4ZDktOGVlOC00YWJjLThlN2EtOTg5MWZjMmQ1NmZhIiwicyI6Ill6TTFaRFF5TW1NdE5tVTVaQzAwTWpOa0xXSTFOR1F0Wm1RMFlXUmhObUppTUdOaSJ9"
