apiVersion: v1
kind: Secret
metadata:
  name: restaurant-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "restaurant-system.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
