apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: restaurant-system
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/shadrachdoc/Restaurant_management.git
    targetRevision: HEAD
    path: helm/restaurant-system
    helm:
      releaseName: restaurant-system
      valueFiles:
        - values.yaml
      parameters:
        - name: global.imageRegistry
          value: docker.io
        - name: posService.enabled
          value: "false"

  destination:
    server: https://kubernetes.default.svc
    namespace: restaurant-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/instance: restaurant-system

  revisionHistoryLimit: 10
