apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service
  namespace: restaurant-system
  labels:
    app: integration-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: integration-service
  template:
    metadata:
      labels:
        app: integration-service
    spec:
      containers:
      - name: integration-service
        image: shadrach85/integration-service:v1.5
        imagePullPolicy: Always
        ports:
        - containerPort: 8015
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: restaurant-config
              key: DATABASE_URL
        - name: ORDER_SERVICE_URL
          value: "http://order-service:8004"
        - name: ENVIRONMENT
          value: "sandbox"
        - name: UBER_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: integration-secrets
              key: uber_client_secret
        - name: WEBHOOK_USERNAME
          valueFrom:
            secretKeyRef:
              name: integration-secrets
              key: webhook_username
        - name: WEBHOOK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: integration-secrets
              key: webhook_password
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8015
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8015
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: integration-service
  namespace: restaurant-system
  labels:
    app: integration-service
spec:
  type: ClusterIP
  ports:
    - port: 8015
      targetPort: 8015
      protocol: TCP
      name: http
  selector:
    app: integration-service
